apiVersion: apps/v1
kind: Deployment
metadata:
  name: byondbot
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      project: byondbot
  template:
    metadata:
      labels:
        project: byondbot
    spec:
      containers:
      - name: byondbot
        image: byond/byondbot:latest
        envFrom:
          - secretRef:
              name: byondbot
          - configMapRef:
              name: build-number
